# -*- coding: utf-8 -*-
"""Tables_Extraction_Uisng_Tabula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RwSMa9XQSoZVJRpv0HyIsF7Eff4guWzE
"""

!pip install -q tabula-py
import tabula

tables = tabula.read_pdf("/content/ap150w-data-sheet.pdf",pages="all")

len(tables)

for i in range(len(tables)):
  print("Table "+str(i+1)+" : ")
  print(tables[i])
  print("*"*50)

